# Generated by Django 5.0.4 on 2024-05-21 21:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.PositiveSmallIntegerField()),
                ('peso', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('sku', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('imagen', models.ImageField(blank=True, upload_to='productos/%Y/%m/%d')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.RemoveField(
            model_name='preciostock',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='price',
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria'], name='tienda_prod_categor_63fe01_idx'),
        ),
        migrations.AddField(
            model_name='productoitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='tienda.producto'),
        ),
        migrations.DeleteModel(
            name='PrecioStock',
        ),
    ]
