# Generated by Django 5.0.4 on 2024-05-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_productoitem_remove_preciostock_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='productoitem',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
