# Generated by Django 5.0.4 on 2024-05-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=50)),
                ('indice', models.IntegerField(blank=True, null=True)),
                ('texto', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='secciones')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(choices=[('nosotros', 'Nosotros')], default='nosotros', max_length=10)),
            ],
            options={
                'ordering': ['indice'],
            },
        ),
    ]
